### ISSUE TITLE
Random Dice role using unicode

### ISSUE THREAD

**Issue by RidhamRj** [Clueless-Community/GUI-Projects#14]
dice rolling gui using tkinter

![image](https://user-images.githubusercontent.com/86556438/197017977-1649b4a5-e69c-44ea-8f57-45b7958ac590.png)

**Comment by RidhamRj** [comment]
@nikhil25803 kindly look forward to it

**Comment by nikhil25803** [comment]
Go ahead @RidhamRj :)

**Comment by nikhil25803** [comment]
Thanks for contributing @RidhamRj :)
