### ISSUE TITLE
Add a language translator GUI project.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/GUI-Projects#34]

**Comment by william-monroy** [comment]
Hi @nikhil25803, I'd like to work on this issue. But when I look for a free API for translations I didn't find anything. My question is: Do you need only the UI or a functional project?

**Comment by nikhil25803** [comment]
Hey @william-monroy, not only the UI, we want you to add functionality to it too.

**Comment by MihirRajeshPanchal** [comment]
@nikhil25803 can you assign me this task?

**Comment by nikhil25803** [comment]
Okay, go ahead @MihirRajeshPanchal
