### ISSUE TITLE
Create CONTRIBUTION.md file

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/GUI-Projects#5]
**Note**
Make  a `CONTRIBUTION.md` file mentioning all the guidelines needed to contribute to this repository

**Comment by SohamG934** [comment]
Hii, I would like to work on this, could you assign me?

**Comment by nikhil25803** [comment]
Sure @SohamG934, go ahead

**Comment by SohamG934** [comment]
hii, can you please inform me about all the guidelines to be included?

**Comment by MihirRajeshPanchal** [comment]
@nikhil25803 can you assign me this task?

**Comment by nikhil25803** [comment]
> @nikhil25803 can you assign me this task?
> 

Go ahead @MihirRajeshPanchal :)
